backend:
  name: git-gateway
  branch: main

media_folder: "public/images/blog"
public_folder: "/images/blog"

collections:
  - name: "blog"
    label: "Artículos"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Fecha de publicación", name: "pubDate", widget: "datetime" }
      - { label: "Imagen de portada", name: "heroImage", widget: "image" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
